# questions.toml

[easy]
label = "Easy Mode"

[[easy.questions]]
question = "What does 'HTML' stand for? "
answers = ["hypertext markup language"]
alternatives = [
    "hypertitle makeup language",
    "hyper text markup language"
]

[[easy.questions]]
question = "Which built-in function can get information from the user?"
answers = ["input"]
alternatives = [
    "get", 
    "print", 
    "write"
]

[[easy.questions]]
question = "What does 'CSS' stand for?"
answers = ["Cascading style sheets"]
alternatives = [
    "Cascading sheets style",
    "Control sample styles",
    "Contact style sheets",
]

[[easy.questions]]
question = "What does dict.get(key) return if key isn't found in dict"
answers = ["None"]
alternatives = ["key", "True", "False"]

[[easy.questions]]
question = "How do you iterate over both indices and elements in an iterable"
answers = ["enumerate(iterable)"]
alternatives = [
    "enumerate(iterable, start=1)",
    "range(iterable)",
    "range(iterable, start=1)",
]

[[easy.questions]]
question = "What's the official name of the := operator"
answers = ["Assignment expression"]
alternatives = [
    "Named expression",
    "Walrus operator",
    "Colon equals operator",
]

[[easy.questions]]
question = "What's one effect of calling random.seed(42)"
answers = ["The random numbers are reproducible."]
alternatives = [
    "The random numbers are more random.",
    "The computer clock is reset.",
    "The first random number is always 42.",
]

[[easy.questions]]
question = "How can you run a Python script named quiz.py"
answers = ["python quiz.py", "python -m quiz"]
alternatives = ["python quiz", "python -m quiz.py"]

[[easy.questions]]
question = "What's the name of the list-like data structure in TOML"
answers = ["Array"]
alternatives = ["List", "Sequence", "Set"]


[[easy.questions]]
question = "How can you add a docstring to a function"
answers = [
    "By writing a string literal as the first statement in the function",
]
alternatives = [
    "By using the built-in @docstring decorator",
    "By returning a string from the function",
]

[normal]
label = "Normal Mode"


[[normal.questions]]
question = "Which version of Python is the first with TOML support built in"
answers = ["3.11"]
alternatives = [
    "3.9", 
    "3.10", 
    "3.12"
]

[[normal.questions]]
question = "What's the capital of Norway"
answers = ["Oslo"]

[[normal.questions]]
question = "What's the state capital of Texas, USA"
answers = ["Austin"]
alternatives = ["Harrisburg", "Houston", "Galveston", "Columbia"]

[hard]
label = "Hard Mode"

[[hard.questions]]
question = "Best language to use for developing a website"
answers = ["HTML"]
alternatives = [
    "Javascript", 
    "CSS", 
    "Python"
]

[[hard.questions]]
question = "When was the first public version of Python released"
answers = ["February 1991"]
alternatives = ["January 1994", "October 2000", "December 2008"]

[[hard.questions]]
question = "What's a PEP"
answers = ["A Python Enhancement Proposal"]
alternatives = [
    "A Pretty Exciting Policy",
    "A Preciously Evolved Python",
    "A Potentially Epic Prize",
]